// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAijVMA50FcTltBgBGBxpZZ9mFOKJwpcZg',
    appId: '1:661878093654:web:2ec82c0efdd84e69e048f7',
    messagingSenderId: '661878093654',
    projectId: 'monitorairlaut',
    authDomain: 'monitorairlaut.firebaseapp.com',
    databaseURL:
        'https://monitorairlaut-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitorairlaut.firebasestorage.app',
    measurementId: 'G-E17VXSYW70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXloYnsHwp4Id7gFWZ1ClDk_XGt5WIYH0',
    appId: '1:661878093654:android:4f7339cea1bd56afe048f7',
    messagingSenderId: '661878093654',
    projectId: 'monitorairlaut',
    databaseURL:
        'https://monitorairlaut-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitorairlaut.firebasestorage.app',
  );
}
